name: utils
version: 0.0.0
author: Andrea Cantafio
description: A sample command-line application
environment:
  sdk: 1.2.0
dependencies:
  args: '>=0.10.0+2 <0.11.0'
  hop: '>=0.30.3 <0.31.0'
  hop_docgen: 0.1.2+2
  path: ">=1.1.0 <2.0.0"
  unittest: '>=0.10.1+2 <0.11.0'
